### ISSUE TITLE
Form Alter the Menu Tree Form

### ISSUE THREAD

**Issue by midnightLuke** [LonDUG/menu_position#16]
Menu Position Rule Links should always _show_ as enabled on this form, even though they never are enabled.

**Comment by midnightLuke** [comment]
Note, they enabled/disabled dynamically based on the config for `menu_position.settings.link_display`.

**Comment by star-szr** [comment]
Just want to note that enabling/disabling a menu position rule's dummy menu link seems to implode it.

**Comment by midnightLuke** [comment]
This was fixed by b38e975acc88cfb561c9868a1d95cd7fea961f1f
