### ISSUE TITLE
Message when creating a new rule is too generic

### ISSUE THREAD

**Issue by star-szr** [LonDUG/menu_position#23]
"Rule has been modified." doesn't sound right for creating a new rule.

**Comment by midnightLuke** [comment]
Evidently `$rule->isNew()` returns false after calling `$rule->save()` in `MenuPositionRuleForm.php`... Seems obvious now, just need a patch to work around it.

**Comment by midnightLuke** [comment]
Fixed by @ckaotik in aeaa15ee9d55a7420583bf040100d68f42b34fc0
