### ISSUE TITLE
Unable to translate Menu Position rules with Configuration Translation

### ISSUE THREAD

**Issue by star-szr** [LonDUG/menu_position#32]
Steps to reproduce:
1. Clean install of Drupal 8, standard profile.
2. Install menu_position.
3. Install config_translation.
4. Create at least one menu position rule via /admin/structure/menu-position/add.
5. Navigate to /admin/config/regional/config-translation/menu_position_rule.

The menu position rule names show up blank.

![image](https://cloud.githubusercontent.com/assets/327943/15951350/920de192-2e85-11e6-8bb9-bbb11cdfa3e5.png)

**Comment by midnightLuke** [comment]
Fixed with #53
