### ISSUE TITLE
Change default "When a menu position rule matches" setting

### ISSUE THREAD

**Issue by star-szr** [LonDUG/menu_position#40]
I think the 80% use case is `Mark the rule's parent menu item as being "active".` rather than `Insert the current page's title into the menu tree.`. At my dayjob I don't think we've ever used `Insert the current page's title into the menu tree`, it's just been an extra setup step when using this module.

For some history:

https://www.drupal.org/node/1019342
https://www.drupal.org/node/1309050

**Comment by midnightLuke** [comment]
Yes please.
