### ISSUE TITLE
Menu Position Rule Plugins

### ISSUE THREAD

**Issue by midnightLuke** [LonDUG/menu_position#9]
We need to figure out how we will implement the plugin system in D8, it seems likely that this will use the new [Plugin API](https://www.drupal.org/developing/api/8/plugins), but I honestly haven't done enough reading on the subject to really know if that will work and/or how it will work.

Important to keep in mind that each plugin will need to provide a form for editing it (that will be used in the vertical tabs of the menu position rule form).

If someone could outline a roadmap for how we are going to implement the plugins that would be great, then we can start knocking them off one by one as they pop up.

**Comment by midnightLuke** [comment]
Alright so we have moved forward with the core "ConditionType" plugins as the primary provider of menu position rule plugins, the next step is to implement our own "Condition" plugin for any legacy menu position plugins not provided in core (Taxonomy Term springs to mind, I think there is some user one as well).  Depending on whether these are applicable or not we may want to somehow block them from the Block form or split them into their own module, as they may be useful _without_ the menu position module and having to this module simply to gain access to new conditions for blocks seems silly.

...it also just occurred to me that a module for additional conditions may already exist, should investigate that.

**Comment by ckaotik** [comment]
Some Conditions are provided as part of other modules (e.g. [Rules](https://www.drupal.org/project/rules)) or as standalone (e.g. [Term Condition](https://www.drupal.org/project/term_condition), [Token Conditions](https://www.drupal.org/project/token_conditions), [Module Conditions](https://www.drupal.org/project/module_conditions)).

The rules module already comes with a ton of conditions (http://cgit.drupalcode.org/rules/tree/src/Plugin/Condition?h=8.x-3.x), however, the last time I used it they did not seem to work reliably, e.g. configuring ones like "Node is sticky" only provided the "Negate" option, and no way to check the option itself.

[Term Condition](https://www.drupal.org/project/term_condition) probably relates to #12 but as per the module description only applies to nodes (Would we need this entity agnostic? I'd think so).

**Comment by midnightLuke** [comment]
Thanks for the tip! This is awesome news, we just need to test these modules with menu_position then and see if they work.

As for "entity agnostic", the way I understand it the `Condition`s that require additional `Context`s also define how they should get said context (ie from a node page vs term page) so it sounds like this one may not work out of the box with ours (at least not the way the original menu_position module plugins did), but there may be opportunities to submit additional plugins to that project that work differently (ie extract the term from the term page as a separate condition or option).

Essentially I think writing Condition plugins and including them in this project is counter-productive unless they are _only_ applicable to the menu position module, but I could be wrong/crazy 😛 .

**Comment by midnightLuke** [comment]
Alright we have gone around this so I am officially closing this issue, though we may eventually re-open it at some point in the future.
